name: Code Sanitizers

on: [push, pull_request, workflow_dispatch]

jobs:
  linux_sanitizers:
    name: Linux [${{ matrix.SANITIZER }}] [${{ matrix.BACKEND }} | ${{ matrix.COMPILER }}]
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        BACKEND: [lmdb, rocksdb]
        COMPILER: [clang]
        SANITIZER: [ASAN, ASAN_INT, TSAN]
    runs-on: ubuntu-22.04
    env:
      COMPILER: ${{ matrix.COMPILER }}
      BACKEND: ${{ matrix.BACKEND }}
      SANITIZER: ${{ matrix.SANITIZER }}
      TEST_USE_ROCKSDB: ${{ matrix.BACKEND == 'rocksdb' && '1' || '0' }}
      DEADLINE_SCALE_FACTOR: ${{ matrix.BACKEND == 'rocksdb' && '2' || '1' }}
      ASAN_OPTIONS: log_exe_name=1:log_path=sanitizer_report
      TSAN_OPTIONS: log_exe_name=1:log_path=sanitizer_report:suppressions=../tsan_suppressions
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Prepare
        run: sudo -E ci/prepare/linux/prepare.sh

      - name: Build Tests
        id: build
        run: ci/build-tests.sh

      - name: Core Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        continue-on-error: true
        run: timeout -sKILL 45m ../ci/tests/run-core-tests.sh
        working-directory: build

      - name: RPC Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        continue-on-error: true
        run: timeout -sKILL 20m ../ci/tests/run-rpc-tests.sh
        working-directory: build

      - name: Reports
        if: steps.build.outcome == 'success' && (success() || failure())
        continue-on-error: true
        run: ../ci/tests/show-sanitizer-reports.sh
        working-directory: build
